name: CI pipeline
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'dev'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_DEV_SERVER_URL: ${{ secrets.NEXT_PUBLIC_DEV_SERVER_URL }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.10'
      - name: get node version
        id: node
        run: |
          echo ":set-output name=node_version::$(node -v)"
      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.node_version }}
      - name: install dependencies
        run: yarn
      - name: run tests
        run: yarn test
      - name: build code
        run: yarn build
