name: CI pipeline

on:
  pull_request:
    branches: [dev, amin]
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      # https://turbo.build/repo/docs/ci/github-actions#caching-with-github-actionscache
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Set up Node...
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: get node version
        id: node
        run: |
          echo ":set-output name=node_version::$(node -v)"

      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.node_version }}

      - name: install dependencies
        run: yarn

      - name: run lint
        run: yarn lint

      - name: build code
        run: yarn build
